trigger: none
pr: none

pool:
  vmImage: windows-latest

stages:
- stage: deploy_mix1
  jobs:
    - job:
      steps:
      - template: templates/cheatcode_template.yaml
        parameters: 
          assetname: mix1
          environment: dev
          location: westus
- stage: deploy_mix2
  jobs:
    - job:
      steps:
      - template: templates/cheatcode_template.yaml
        parameters: 
          assetname: mix2
          environment: dev
          location: westus