trigger: none
pr: none

pool:
  vmImage: windows-latest

stages:

- stage: deploy_dogs
  jobs:
    - job:
      steps:
      - template: templates/cheatcode_template.yaml
        parameters: 
          assetname: dogs
          environment: dev
          location: westus
          serviceconnection: terraform-sp-63498
- stage: deploy_cats
  jobs:
    - job:
      steps:
      - template: templates/cheatcode_template.yaml
        parameters: 
          assetname: cats
          environment: dev
          location: westus
          serviceconnection: terraform-sp-63498

